import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <Link href={"/"}>홈</Link>
          <Link href={"/list"}>List</Link>
          <Link href={"/fruit"}>fruit</Link>
          <Link href={"/cart"}>Cart</Link>
          <Link href={"/blog/slug"}>blog</Link>
          <Link href={"/about"}>about</Link>

        </div>

        {children}
      </body>
    </html>
  );
}
